### ISSUE TITLE
Automate the release process with Release Please

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/kotlin-sdk#4]
```[tasklist]
### Tasks
- [x] Update repo settings to only allow squash merges using the PR title
- [ ] https://github.com/open-feature/kotlin-sdk/issues/15
- [x] Add Release Please GitHub action and initial configuration
- [x] Update the release GitHub action to only run after a Release Please release PR is merged
- [ ] Document the release process
```
